name: Build and deploy Python app to Azure Web App - MoneyMantra

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Update to Python 3.10

      - name: Navigate to Models directory
        run: cd Models

      - name: Create and start virtual environment
        run: |
          cd Models
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          cd Models
          pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: |
          cd Models
          zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            Models/release.zip
            Models/venv/ # Exclude venv folder

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip Models/release.zip -d Models

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4B9ABCB441634A1C9F1697E1FBF7DC27 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B45DD836C8534341AAA85EB5A81834EF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_45479DD19D1E49BFBAAB41DAAEB5C1AA }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'MoneyMantra'
          slot-name: 'Production'
          package: Models/release.zip
